/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSiteCard: typeof import('./components/AboutSiteCard.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    CapabilitiesCard: typeof import('./components/CapabilitiesCard.vue')['default']
    ClassificationResultTable: typeof import('./components/ClassificationResultTable.vue')['default']
    DoughnutChart: typeof import('./components/DoughnutChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    LoadingOverlay: typeof import('./components/LoadingOverlay.vue')['default']
    PageFooter: typeof import('./components/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
